name: drivertube
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  carousel_slider: ^1.3.1
  camera: ^0.5.6+3
  intl: ^0.16.0
  weather: ^0.9.5

  
  flutter:
    sdk: flutter
  


  flutter_localizations:
   sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true


  assets:
  - Assets/local/localization_en.json
  - Assets/local/localization_es.json
  - Assets/images/spleshimage.jpg
  - Assets/images/logo.png
  - Assets/icons/filter.png
  - Assets/images/BadLight9.jpg
  - Assets/images/DangerousDriving2.jpg
  - Assets/images/Others10.jpg
  - Assets/images/OvertakingReport6.jpg
  - Assets/images/Parking1.jpg
  - Assets/images/PedestrianViolation5.jpg
  - Assets/images/RedLight3.jpg
  - Assets/images/Sped4.jpg
  - Assets/images/Taxi-BusReport8.jpg
  - Assets/images/TrafficSignsReport7.jpg
  - Assets/icons/Home.png
  - Assets/icons/Search.png
  - Assets/icons/Profile.png
  - Assets/icons/Notification.png
  - Assets/icons/Category.png
  - Assets/icons/Clock.png
  - Assets/icons/Location.png
  - Assets/icons/SortBy.png
  - Assets/icons/Path.png
  - Assets/icons/Notificationfill.png
  - Assets/icons/Language.png
  - Assets/icons/Terms.png
  - Assets/icons/Privacy.png
  - Assets/icons/Help.png
  - Assets/icons/UserName.png
  - Assets/icons/FullName.png 
  - Assets/icons/Email.png
  - Assets/icons/Gender.png 
  - Assets/icons/Camera.png
  - Assets/icons/Photos.png
  - Assets/icons/DoneIcon.png
  - Assets/icons/SavedPosts.png
  - Assets/icons/SignOut.png
  - Assets/icons/OnSwitch.png
  - Assets/icons/OffSwitch.png 
  - Assets/images/UsaFlag.png
  - Assets/images/SpainFlag.png
  - Assets/images/GermanFlag.png
  - Assets/images/TurkeyFlag.png
  - Assets/icons/Message.png
  - Assets/icons/NoNetwork.png
  - Assets/icons/Close.png
  - Assets/icons/Weather.png
  - Assets/icons/Postanon.png
  - Assets/icons/Preview.png
  - Assets/icons/Searchdull.png
  - Assets/icons/Cancel.png
  - Assets/icons/delete.png
  - Assets/icons/Video.png
  - Assets/icons/FaceIcon.png
  - Assets/icons/CookiePolicy.png
  - Assets/icons/Google.png
  - Assets/icons/Instagram.png
  - Assets/icons/NotificationDec.png
  - Assets/icons/SignIn.png
  - Assets/icons/PersonalDataProtection.png
  - Assets/icons/PersonalDataTerms.png
  
  

  
     
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
